### ISSUE TITLE
Use with react-redux-universal-hot-example

### ISSUE THREAD

**Issue by OKNoah** [captbaritone/raven-for-redux#33]
I've been trying for some time to use this in my app based on erikras/react-redux-universal-hot-example.

Whenever I throw an error in a reducer, no request is sent to Sentry.

I have done a lot of configuration, reconfiguration and such, including implementing Rasmusen's great `./ApiClient` into the the `./examples` here, but that worked as expected. As a result I have not narrowed down the issue to that part.

Here is the [relevant (I think) section of Rasmussen'a repo](https://github.com/erikras/react-redux-universal-hot-example/tree/master/src/redux).

Any quick insight from someone more experienced the I would be greatly appreciated.

**Comment by captbaritone** [comment]
I'm not entirely sure what you're asking. Could you share a minimal example of what you are currently trying, what you expect to happen and what is acuay happening along with any relevant errors or context?

Also, if you are just looking for help setting up the package, rather than reporting an bug/issue with the package, Stack Overflow may be a better venue that GitHub issues.

Feel free to send me a link to the stack overflow issue, and I can try to help you over there.
